// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from "../Components/Navbar";
// import Footer from "../Components/Footer";
// import SessionWrapper from "./(home)/Components/SessionWrapper";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Book Collection",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <SessionWrapper>
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//         >
//         <Navbar/>
//         {children}
//         <Footer/>
//       </body>
//       </SessionWrapper>
//     </html>
//   );
// }


//only deplot time bug occure 
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../Components/Navbar";
import Footer from "../Components/Footer";
import SessionWrapper from "./(home)/Components/SessionWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Doctor Collection",
  description: "Generated by create next app",
};

// Define session type
// interface Session {
//   user: {
//     name: string;
//     email: string;
//   };
//   isAuthenticated: boolean;
// }

export default function RootLayout({
  children,
  // session, // Ensure session is passed
}: Readonly<{
  children: React.ReactNode;
  // session?: Session;
}>) {
  return (
    <html lang="en">
        <SessionWrapper >
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <Navbar />
          <main>{children}</main>
          <Footer />
      </body>
        </SessionWrapper>
    </html>
  );
}


// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from "../Components/Navbar";
// import Footer from "../Components/Footer";
// import { SessionProvider } from "next-auth/react"; // Import SessionProvider here

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Book Collection",
//   description: "Generated by create next app",
// };

// // No need to define Session type here, it's handled by next-auth

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//         <SessionProvider> {/* SessionProvider wraps everything */}
//           <Navbar />
//           <main>{children}</main>
//           <Footer />
//         </SessionProvider>
//       </body>
//     </html>
//   );
// }